import type { Metadata } from "next";
import "./globals.css";
import Menu from "../components/Menu";

export const metadata: Metadata = {
  title: "participate",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><Menu />{children}</body>
    </html>
  );
}
